{"name": "Авторизация с недействительными учетными данными", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at C:\\Users\\asya4\\AppData\\Local\\ms-playwright\\chromium-1134\\chrome-win\\chrome.exe\n╔════════════════════════════════════════════════════════════╗\n║ Looks like Playwright was just installed or updated.       ║\n║ Please run the following command to download new browsers: ║\n║                                                            ║\n║     playwright install                                     ║\n║                                                            ║\n║ <3 Playwright Team                                         ║\n╚════════════════════════════════════════════════════════════╝", "trace": "launch_browser = <function launch_browser.<locals>.launch at 0x00000244DB96AA20>\n\n    @pytest.fixture(scope=\"session\")\n    def browser(launch_browser: Callable[[], Browser]) -> Generator[Browser, None, None]:\n>       browser = launch_browser()\n\n..\\..\\..\\.virtualenvs\\.venv-yUu4ZoCJ\\Lib\\site-packages\\pytest_playwright\\pytest_playwright.py:266: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\.virtualenvs\\.venv-yUu4ZoCJ\\Lib\\site-packages\\pytest_playwright\\pytest_playwright.py:258: in launch\n    browser = browser_type.launch(**launch_options)\n..\\..\\..\\.virtualenvs\\.venv-yUu4ZoCJ\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:14153: in launch\n    self._sync(\n..\\..\\..\\.virtualenvs\\.venv-yUu4ZoCJ\\Lib\\site-packages\\playwright\\_impl\\_browser_type.py:95: in launch\n    Browser, from_channel(await self._channel.send(\"launch\", params))\n..\\..\\..\\.virtualenvs\\.venv-yUu4ZoCJ\\Lib\\site-packages\\playwright\\_impl\\_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x00000244DB986990>\ncb = <function Channel.send.<locals>.<lambda> at 0x00000244DBA00E00>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at C:\\Users\\asya4\\AppData\\Local\\ms-playwright\\chromium-1134\\chrome-win\\chrome.exe\nE           ╔════════════════════════════════════════════════════════════╗\nE           ║ Looks like Playwright was just installed or updated.       ║\nE           ║ Please run the following command to download new browsers: ║\nE           ║                                                            ║\nE           ║     playwright install                                     ║\nE           ║                                                            ║\nE           ║ <3 Playwright Team                                         ║\nE           ╚════════════════════════════════════════════════════════════╝\n\n..\\..\\..\\.virtualenvs\\.venv-yUu4ZoCJ\\Lib\\site-packages\\playwright\\_impl\\_connection.py:514: Error"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1728403061092, "stop": 1728403061092, "uuid": "905e401e-a4d2-45a7-83fc-d4effc08e66b", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "feature", "value": "Авторизация"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "Авторизация недействительные учетные данные"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "35356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}